### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by XiaoBai-collab** [ohhhyeahhh/SiamCAR#21]
An error occurred when I used the OTB dataset for evaluation and testing.
loading OTB50: 50%|██████████████████▌ | 25/50 [00:00<00:00, 213.24it/s, Human4-2]
Traceback (most recent call last):
File "eval.py", line 106, in <module>
main()
File "eval.py", line 46, in main
dataset = OTBDataset(args.dataset, root)
File "../toolkit/datasets/otb.py", line 102, in __init__
load_img)
File "../toolkit/datasets/otb.py", line 27, in __init__
init_rect, img_names, gt_rect, attr, load_img)
File "../toolkit/datasets/video.py", line 27, in __init__
assert img is not None, self.img_names[0]
AssertionError: /home/xiaobai/PycharmProjects/Object Tracking Code/DLCode/data/OTB50/Human4-2/img/0001.jpg
Excuse me, how can I solve this problem?

**Comment by twotwo2** [comment]
Try to change the file name "Human4_2" to "Human4-2".

**Comment by XiaoBai-collab** [comment]
> Try to change the file name "Human4_2" to "Human4-2".

Ok, i'll try it again. Thanks for your reply.

**Comment by 1234wyj** [comment]
> An error occurred when I used the OTB dataset for evaluation and testing. loading OTB50: 50%|██████████████████▌ | 25/50 [00:00<00:00, 213.24it/s, Human4-2] Traceback (most recent call last): File "eval.py", line 106, in main() File "eval.py", line 46, in main dataset = OTBDataset(args.dataset, root) File "../toolkit/datasets/otb.py", line 102, in **init** load_img) File "../toolkit/datasets/otb.py", line 27, in **init** init_rect, img_names, gt_rect, attr, load_img) File "../toolkit/datasets/video.py", line 27, in **init** assert img is not None, self.img_names[0] AssertionError: /home/xiaobai/PycharmProjects/Object Tracking Code/DLCode/data/OTB50/Human4-2/img/0001.jpg Excuse me, how can I solve this problem?

Did you solve the problem? I have the same problem

**Comment by CassandraClare** [comment]
> > Try to change the file name "Human4_2" to "Human4-2".
> 
> Ok, i'll try it again. Thanks for your reply.

I am also having the same problem. If you were able to solve it then please let me know how.
