### ISSUE TITLE
训练的问题？

### ISSUE THREAD

**Issue by mr-xiao-zuo** [ohhhyeahhh/SiamCAR#25]
单独训练LaSOT数据集，修改了config.py中的__C.DATASET.NAMES=('LaSOT')和config.yaml中的DATASET:NAMES: - 'LaSOT'之后，执行train.py，报如下错误，请问什么原因造成的呢？
Traceback (most recent call last):
  File "/home/dl/code/SiamCAR-master/tools/train.py", line 315, in <module>
    main()
  File "/home/dl/code/SiamCAR-master/tools/train.py", line 310, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "/home/dl/code/SiamCAR-master/tools/train.py", line 171, in train
    for idx, data in enumerate(train_loader):
  File "/home/dl/anaconda3/envs/siamcar/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/dl/anaconda3/envs/siamcar/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/dl/anaconda3/envs/siamcar/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dl/anaconda3/envs/siamcar/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dl/anaconda3/envs/siamcar/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dl/anaconda3/envs/siamcar/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dl/code/SiamCAR-master/pysot/datasets/dataset.py", line 248, in __getitem__
    template_box = self._get_bbox(template_image, template[1])
  File "/home/dl/code/SiamCAR-master/pysot/datasets/dataset.py", line 207, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Process finished with exit code 1

**Comment by WangJun-ZJUT** [comment]
Thank you for your question. This problem is usually caused by a wrong path. We suggest that you should check the path of datasets .

**Comment by Bennett-H** [comment]
您好,我想问一下,为什么我训练出来的模型没有代码给定的效果那么好?

**Comment by eilo1234** [comment]
> 您好,我想问一下,为什么我训练出来的模型没有代码给定的效果那么好?

我也遇到了这个问题，请问你后来有解决吗？

**Comment by mr-xiao-zuo** [comment]
> > 您好,我想问一下,为什么我训练出来的模型没有代码给定的效果那么好?
> 
> 我也遇到了这个问题，请问你后来有解决吗？

请问你解决这个问题了吗？

**Comment by Bennett-H** [comment]
> > > 您好,我想问一下,为什么我训练出来的模型没有代码给定的效果那么好?
> > 
> > 
> > 我也遇到了这个问题，请问你后来有解决吗？
> 
> 请问你解决这个问题了吗？
DET的数据集加载出了错

**Comment by Bennett-H** [comment]
> > > 您好,我想问一下,为什么我训练出来的模型没有代码给定的效果那么好?
> > 
> > 
> > 我也遇到了这个问题，请问你后来有解决吗？
> 
> 请问你解决这个问题了吗？

在训练时,没有加载DET数据集。

**Comment by mr-xiao-zuo** [comment]
> 您好,我想问一下,为什么我训练出来的模型没有代码给定的效果那么好?

您训练到最后总的损失是多少呢？

**Comment by Giveupfree** [comment]
同问，GOT10K版本和作者的差了10个点左右，会不会作者的结果有问题

**Comment by Mionger** [comment]
你好，请问您这个问题解决了吗，应该怎么处理呢

**Comment by chenxlin222** [comment]
您好，想请教个问题：如果只用got-10k训练，需要修改__C.DATASET.GOT.NUM_USE (100000)， __C.DATASET.VIDEOS_PER_EPOCH (600000)，__C.TRAIN.EPOCH (20)这些参数吗？如果不修改的话，就会有20*600000数据量，训练时间太太太长了，如果修改，应该改成多少比较合适呢？
