### ISSUE TITLE
test.py 的hp_search错误

### ISSUE THREAD

**Issue by panjialei123** [ohhhyeahhh/SiamCAR#33]
Traceback (most recent call last):
  File "test.py", line 126, in <module>
    main()
  File "test.py", line 51, in main
    params = getattr(cfg.HP_SEARCH,args.dataset)
  File "D:\Anaconda3\envs\pytracking\lib\site-packages\yacs\config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: rsvideo

作者你好，我在test数据集rsvideo，已经在toolkit/datasets中添加相应的代码，但是在test.py51行中的hp_search中报错，请问一下怎么解决

**Comment by WangJun-ZJUT** [comment]
Hi, you should also add the code for your datasets at pysot/core/config.py.

**Comment by WangJun-ZJUT** [comment]
Hi, please also add the code for your datasets at pysot/core/config.py.
