### ISSUE TITLE
如何单独训练某一训练集？

### ISSUE THREAD

**Issue by aaahuia** [ohhhyeahhh/SiamCAR#36]
修改了config.py中的__C.DATASET.NAMES，但是还是会优先载入VID，请问还需要修改哪里，谢谢

**Comment by WangJun-ZJUT** [comment]
Hi,please modify the parameter DATASET.NAMES in experiences / siamcar_ r50/ config.yaml.

**Comment by aaahuia** [comment]
> Hi,please modify the parameter DATASET.NAMES in experiences / siamcar_ r50/ config.yaml.

Thank you for your reply. The problem has been solved.

**Comment by aaahuia** [comment]
Thank you for your reply. The problem has been solved




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WangJun-ZJUT"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 中午1:32
收件人: "ohhhyeahhh/SiamCAR"<SiamCAR@noreply.github.com&gt;; 
抄送: "O(∩_∩)O~"<1076032567@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36)





 
Hi,please modify the parameter DATASET.NAMES in experiences / siamcar_ r50/ config.yaml.

**Comment by aaahuia** [comment]
Thank you for your reply！
Now I have a new problem。
Just like the question “训练的问题？”in github
Your answer is “This problem is usually caused by a wrong path. We suggest that you should check the path of datasets .”
Can you explain it in more detail？
Isn't the path of dataset fixed？

Thank you very much！




&nbsp; File "G:\practice\SiamCAR-master\tools\train.py", line 320, in <module&gt;
&nbsp; &nbsp; main()


&nbsp; File "G:\practice\SiamCAR-master\tools\train.py", line 315, in main
&nbsp; &nbsp; train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)


&nbsp; File "G:\practice\SiamCAR-master\tools\train.py", line 175, in train
&nbsp; &nbsp; for idx, data in enumerate(train_loader):


&nbsp; File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
&nbsp; &nbsp; return self._process_next_batch(batch)


&nbsp; File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
&nbsp; &nbsp; raise batch.exc_type(batch.exc_msg)


AttributeError: Traceback (most recent call last):
&nbsp; File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
&nbsp; &nbsp; samples = collate_fn([dataset[i] for i in batch_indices])
&nbsp; File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in <listcomp&gt;
&nbsp; &nbsp; samples = collate_fn([dataset[i] for i in batch_indices])
&nbsp; File "..\pysot\datasets\dataset.py", line 248, in __getitem__
&nbsp; &nbsp; template_box = self._get_bbox(template_image, template[1])
&nbsp; File "..\pysot\datasets\dataset.py", line 207, in _get_bbox
&nbsp; &nbsp; imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WangJun-ZJUT"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 中午1:32
收件人: "ohhhyeahhh/SiamCAR"<SiamCAR@noreply.github.com&gt;; 
抄送: "O(∩_∩)O~"<1076032567@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36)





 
Hi,please modify the parameter DATASET.NAMES in experiences / siamcar_ r50/ config.yaml.

**Comment by bibixiuxiuxiu** [comment]
请问训练过程出现AttributeError: 'NoneType' object has no attribute 'shape'错误，怎么解决呢，

**Comment by bibixiuxiuxiu** [comment]
> Thank you for your reply！ Now I have a new problem。 Just like the question “训练的问题？”in github Your answer is “This problem is usually caused by a wrong path. We suggest that you should check the path of datasets .” Can you explain it in more detail？ Isn't the path of dataset fixed？ Thank you very much！ &nbsp; File "G:\practice\SiamCAR-master\tools\train.py", line 320, in <module&gt; &nbsp; &nbsp; main() &nbsp; File "G:\practice\SiamCAR-master\tools\train.py", line 315, in main &nbsp; &nbsp; train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer) &nbsp; File "G:\practice\SiamCAR-master\tools\train.py", line 175, in train &nbsp; &nbsp; for idx, data in enumerate(train_loader): &nbsp; File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__ &nbsp; &nbsp; return self._process_next_batch(batch) &nbsp; File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch &nbsp; &nbsp; raise batch.exc_type(batch.exc_msg) AttributeError: Traceback (most recent call last): &nbsp; File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop &nbsp; &nbsp; samples = collate_fn([dataset[i] for i in batch_indices]) &nbsp; File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in <listcomp&gt; &nbsp; &nbsp; samples = collate_fn([dataset[i] for i in batch_indices]) &nbsp; File "..\pysot\datasets\dataset.py", line 248, in __getitem__ &nbsp; &nbsp; template_box = self._get_bbox(template_image, template[1]) &nbsp; File "..\pysot\datasets\dataset.py", line 207, in _get_bbox &nbsp; &nbsp; imh, imw = image.shape[:2] AttributeError: 'NoneType' object has no attribute 'shape'
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WangJun-ZJUT"<notifications@github.com&gt;; 发送时间: 2020年11月11日(星期三) 中午1:32 收件人: "ohhhyeahhh/SiamCAR"<SiamCAR@noreply.github.com&gt;; 抄送: "O(∩_∩)O~"<1076032567@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36) Hi,please modify the parameter DATASET.NAMES in experiences / siamcar_ r50/ config.yaml. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

老哥 请问这个问题具体怎么解决的呢

**Comment by Mionger** [comment]
> > Thank you for your reply！ Now I have a new problem。 Just like the question “训练的问题？”in github Your answer is “This problem is usually caused by a wrong path. We suggest that you should check the path of datasets .” Can you explain it in more detail？ Isn't the path of dataset fixed？ Thank you very much！   File "G:\practice\SiamCAR-master\tools\train.py", line 320, in <module>     main()   File "G:\practice\SiamCAR-master\tools\train.py", line 315, in main     train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)   File "G:\practice\SiamCAR-master\tools\train.py", line 175, in train     for idx, data in enumerate(train_loader):   File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 336, in **next**     return self._process_next_batch(batch)   File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch     raise batch.exc_type(batch.exc_msg) AttributeError: Traceback (most recent call last):   File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop     samples = collate_fn([dataset[i] for i in batch_indices])   File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in <listcomp>     samples = collate_fn([dataset[i] for i in batch_indices])   File "..\pysot\datasets\dataset.py", line 248, in **getitem**     template_box = self._get_bbox(template_image, template[1])   File "..\pysot\datasets\dataset.py", line 207, in _get_bbox     imh, imw = image.shape[:2] AttributeError: 'NoneType' object has no attribute 'shape'
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "WangJun-ZJUT"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年11月11日(星期三) 中午1:32 收件人: "ohhhyeahhh/SiamCAR"<[SiamCAR@noreply.github.com](mailto:SiamCAR@noreply.github.com)>; 抄送: "O(∩_∩)O~"<[1076032567@qq.com](mailto:1076032567@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36) Hi,please modify the parameter DATASET.NAMES in experiences / siamcar_ r50/ config.yaml. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 老哥 请问这个问题具体怎么解决的呢

老哥，请问这个问题你解决了吗，该咋整啊

**Comment by Znc1996** [comment]
如果不改绝对路径的话，建议更改datasets.py中的self.root路径，把他改成和self.anno一样的格式。我尝试过是可以的

**Comment by Znc1996** [comment]
> > > Thank you for your reply！ Now I have a new problem。 Just like the question “训练的问题？”in github Your answer is “This problem is usually caused by a wrong path. We suggest that you should check the path of datasets .” Can you explain it in more detail？ Isn't the path of dataset fixed？ Thank you very much！   File "G:\practice\SiamCAR-master\tools\train.py", line 320, in      main()   File "G:\practice\SiamCAR-master\tools\train.py", line 315, in main     train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)   File "G:\practice\SiamCAR-master\tools\train.py", line 175, in train     for idx, data in enumerate(train_loader):   File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 336, in **next**     return self._process_next_batch(batch)   File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch     raise batch.exc_type(batch.exc_msg) AttributeError: Traceback (most recent call last):   File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop     samples = collate_fn([dataset[i] for i in batch_indices])   File "E:\anaconda\1\envs\pysot\lib\site-packages\torch\utils\data\dataloader.py", line 106, in      samples = collate_fn([dataset[i] for i in batch_indices])   File "..\pysot\datasets\dataset.py", line 248, in **getitem**     template_box = self._get_bbox(template_image, template[1])   File "..\pysot\datasets\dataset.py", line 207, in _get_bbox     imh, imw = image.shape[:2] AttributeError: 'NoneType' object has no attribute 'shape'
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "WangJun-ZJUT"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年11月11日(星期三) 中午1:32 收件人: "ohhhyeahhh/SiamCAR"<[SiamCAR@noreply.github.com](mailto:SiamCAR@noreply.github.com)>; 抄送: "O(∩_∩)O~"<[1076032567@qq.com](mailto:1076032567@qq.com)>; "Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36) Hi,please modify the parameter DATASET.NAMES in experiences / siamcar_ r50/ config.yaml. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 老哥 请问这个问题具体怎么解决的呢
> 
> 老哥，请问这个问题你解决了吗，该咋整啊

如果不改绝对路径的话，建议更改datasets.py中的self.root路径，把他改成和self.anno一样的格式。我尝试过是可以的

**Comment by chenxlin222** [comment]
您好，想请教个问题：如果只用got-10k训练，需要修改__C.DATASET.GOT.NUM_USE (100000)， __C.DATASET.VIDEOS_PER_EPOCH (600000)，__C.TRAIN.EPOCH (20)这些参数吗？如果不修改的话，就会有20*600000数据量，训练时间太太太长了，如果修改，应该改成多少比较合适呢？

**Comment by Znc1996** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    这个我觉得你可以参考SiamBAN，我觉得只有GOT10K的话，可以设置成10w来着好像，比如__C.DATASET.VIDEOS_PER_EPOCH (100000)。如果你的设备像我一样不太行的话，可以这么做一下试试。但是OTB上的精度肯定达不到原文。
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月7日 15:14
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36)
        
      
    
  
  

您好，想请教个问题：如果只用got-10k训练，需要修改__C.DATASET.GOT.NUM_USE (100000)， __C.DATASET.VIDEOS_PER_EPOCH (600000)，__C.TRAIN.EPOCH (20)这些参数吗？如果不修改的话，就会有20*600000数据量，训练时间太太太长了，如果修改，应该改成多少比较合适呢？

**Comment by chenxlin222** [comment]
好的！谢谢！因为我现在只有一块2080Ti，然后看完SiamCAR的训练代码，感觉好像作者不管用几个数据集训练，这个参数都是设置的20*600000，一样的数据量。但是不应该训练集小的时候，应该相应地改变训练的这些参数吗？






发件人：ZNC-Track ***@***.***>
发送日期：2022-11-07 16:18:44
收件人：ohhhyeahhh/SiamCAR ***@***.***>
抄送人：chenxlin222 ***@***.***>,Comment ***@***.***>
主题：Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36)







font{
 line-height: 1.6;
 }
 ul,ol{
 padding-left: 20px;
 list-style-position: inside;
 }



 这个我觉得你可以参考SiamBAN，我觉得只有GOT10K的话，可以设置成10w来着好像，比如__C.DATASET.VIDEOS_PER_EPOCH (100000)。如果你的设备像我一样不太行的话，可以这么做一下试试。但是OTB上的精度肯定达不到原文。









 ***@***.***





 ---- 回复的原邮件 ----





 发件人


 ***@***.***>





 发送日期


 2022年11月7日 15:14




 收件人




 ***@***.***>






 抄送人



 ***@***.***>
 ,


 ***@***.***>






 主题


 Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36)






 您好，想请教个问题：如果只用got-10k训练，需要修改__C.DATASET.GOT.NUM_USE (100000)， __C.DATASET.VIDEOS_PER_EPOCH (600000)，__C.TRAIN.EPOCH (20)这些参数吗？如果不修改的话，就会有20*600000数据量，训练时间太太太长了，如果修改，应该改成多少比较合适呢？

**Comment by Znc1996** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    这个问题我在之前有问过作者，但是作者并没有回答我的问题。后来我问了一些做跟踪方向的前辈，他们说这地方是不变的。仅供参考，但我觉得你有时间的话，还是以实际效果为主吧。
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月7日 16:47
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36)
        
      
    
  
  
好的！谢谢！因为我现在只有一块2080Ti，然后看完SiamCAR的训练代码，感觉好像作者不管用几个数据集训练，这个参数都是设置的20*600000，一样的数据量。但是不应该训练集小的时候，应该相应地改变训练的这些参数吗？






发件人：ZNC-Track ***@***.***>
发送日期：2022-11-07 16:18:44
收件人：ohhhyeahhh/SiamCAR ***@***.***>
抄送人：chenxlin222 ***@***.***>,Comment ***@***.***>
主题：Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36)







font{
 line-height: 1.6;
 }
 ul,ol{
 padding-left: 20px;
 list-style-position: inside;
 }



 这个我觉得你可以参考SiamBAN，我觉得只有GOT10K的话，可以设置成10w来着好像，比如__C.DATASET.VIDEOS_PER_EPOCH (100000)。如果你的设备像我一样不太行的话，可以这么做一下试试。但是OTB上的精度肯定达不到原文。









 ***@***.***





 ---- 回复的原邮件 ----





 发件人


 ***@***.***>





 发送日期


 2022年11月7日 15:14




 收件人




 ***@***.***>






 抄送人



 ***@***.***>
 ,


 ***@***.***>






 主题


 Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36)






 您好，想请教个问题：如果只用got-10k训练，需要修改__C.DATASET.GOT.NUM_USE (100000)， __C.DATASET.VIDEOS_PER_EPOCH (600000)，__C.TRAIN.EPOCH (20)这些参数吗？如果不修改的话，就会有20*600000数据量，训练时间太太太长了，如果修改，应该改成多少比较合适呢？

**Comment by chenxlin222** [comment]
好的好的！非常感谢您的回复，那我再研究研究，主要是一块卡训练这么多数据，有些太费时间了

**Comment by chenxlin222** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 这个问题我在之前有问过作者，但是作者并没有回答我的问题。后来我问了一些做跟踪方向的前辈，他们说这地方是不变的。仅供参考，但我觉得你有时间的话，还是以实际效果为主吧。 ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2022年11月7日 16:47 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36) 好的！谢谢！因为我现在只有一块2080Ti，然后看完SiamCAR的训练代码，感觉好像作者不管用几个数据集训练，这个参数都是设置的20*600000，一样的数据量。但是不应该训练集小的时候，应该相应地改变训练的这些参数吗？ 发件人：ZNC-Track ***@***.***> 发送日期：2022-11-07 16:18:44 收件人：ohhhyeahhh/SiamCAR ***@***.***> 抄送人：chenxlin222 ***@***.***>,Comment ***@***.***> 主题：Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36) font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 这个我觉得你可以参考SiamBAN，我觉得只有GOT10K的话，可以设置成10w来着好像，比如__C.DATASET.VIDEOS_PER_EPOCH (100000)。如果你的设备像我一样不太行的话，可以这么做一下试试。但是OTB上的精度肯定达不到原文。 ***@***.***
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2022年11月7日 15:14 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [ohhhyeahhh/SiamCAR] 如何单独训练某一训练集？ (#36) 您好，想请教个问题：如果只用got-10k训练，需要修改__C.DATASET.GOT.NUM_USE (100000)， __C.DATASET.VIDEOS_PER_EPOCH (600000)，__C.TRAIN.EPOCH (20)这些参数吗？如果不修改的话，就会有20*600000数据量，训练时间太太太长了，如果修改，应该改成多少比较合适呢？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>— Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

好的好的！非常感谢您的回复，那我再研究研究，主要是一块卡训练这么多数据，有些太费时间了
