### ISSUE TITLE
the same error

### ISSUE THREAD

**Issue by bibixiuxiuxiu** [ohhhyeahhh/SiamCAR#41]
the same error
只用一个数据集进行训练出现AttributeError: 'NoneType' object has no attribute 'shape'
_Originally posted by @AstoncPou in https://github.com/ohhhyeahhh/SiamCAR/issues/37#issuecomment-727189062_

**Comment by WangJun-ZJUT** [comment]
Hi! Please check your dataset path to make sure it can be found.

**Comment by sunset233** [comment]
> Hi! Please check your dataset path to make sure it can be found.

Traceback (most recent call last):
  File "/home/g303/lph/SiamCAR-master/tools/train.py", line 315, in <module>
    main()
  File "/home/g303/lph/SiamCAR-master/tools/train.py", line 310, in main
error image: train_dataset/vid/crop511/a/ILSVRC2015_train_00124006/000074.04.x.jpg
error image: train_dataset/coco/crop511/train2017/000000072935/000000.01.x.jpg
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "/home/g303/lph/SiamCAR-master/tools/train.py", line 171, in train
    for idx, data in enumerate(train_loader):
  File "/home/g303/.conda/envs/ReplusionLoss/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/g303/.conda/envs/ReplusionLoss/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/g303/.conda/envs/ReplusionLoss/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/g303/.conda/envs/ReplusionLoss/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/g303/.conda/envs/ReplusionLoss/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/g303/.conda/envs/ReplusionLoss/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/g303/.conda/envs/ReplusionLoss/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/g303/lph/SiamCAR-master/pysot/datasets/dataset.py", line 248, in __getitem__
    template_box = self._get_bbox(template_image, template[1])
  File "/home/g303/lph/SiamCAR-master/pysot/datasets/dataset.py", line 207, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'


Process finished with exit code 1
他可以打印出图片，但是还是报错了，我应该检查什么文件的配置呢，大佬？
