### ISSUE TITLE
关于HP_SEARCH

### ISSUE THREAD

**Issue by bibixiuxiuxiu** [ohhhyeahhh/SiamCAR#47]
请问对于otb50和vot2018数据集，HP_SEARCH的值应该设置为多少

**Comment by WangJun-ZJUT** [comment]
您好!我们通常用网格搜索的方式搜索参数.

**Comment by Tangzhaotz** [comment]
您好，我采用pysot里面的hp_research调VOT2019的参数，得到结果进行eval时出现这种情况：
请问一下是什么原因
ultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tz/.conda/envs/pysot/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/tz/test_code_siamcarv2/SiamCAR_train1/toolkit/evaluation/eao_benchmark.py", line 47, in eval
    eao = self._calculate_eao(tracker_name, self.tags)
  File "/home/tz/test_code_siamcarv2/SiamCAR_train1/toolkit/evaluation/eao_benchmark.py", line 110, in _calculate_eao
    max_len = max([len(x) for x in all_overlaps])
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tz/test_code_siamcarv2/SiamCAR_train1/tools/eval.py", line 123, in <module>
    main()
  File "/home/tz/test_code_siamcarv2/SiamCAR_train1/tools/eval.py", line 117, in main
    trackers), desc='eval eao', total=len(trackers), ncols=100):
  File "/home/tz/.conda/envs/pysot/lib/python3.7/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/home/tz/.conda/envs/pysot/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
ValueError: max() arg is an empty sequence

**Comment by WangJun-ZJUT** [comment]
您好!可以调试检查一下all_overlaps这个变量存储的数据是否正常

**Comment by Tangzhaotz** [comment]
> 您好!可以调试检查一下all_overlaps这个变量存储的数据是否正常

多谢，我已经解决

**Comment by mrq1102094712** [comment]
Could you share me your HP_SEARCH in VOT datasets, thanks!

**Comment by ghostbreaken** [comment]
> > 您好!可以调试检查一下all_overlaps这个变量存储的数据是否正常
> 
> 多谢，我已经解决

老哥 能咨询一下你是怎么用pysot里面的hp_search.py 调超参数的呢

**Comment by rkj12345** [comment]
> 请问对于otb50和vot2018数据集，HP_SEARCH的值应该设置为多少

请问你在vot数据集上测试效果怎么样啊

**Comment by zhuhuzhenjing** [comment]
同问vot——2018的cfg.HP_SEARCH
