### ISSUE TITLE
测试时目标位置偏移相关的数组越界错误

### ISSUE THREAD

**Issue by Mionger** [ohhhyeahhh/SiamCAR#57]
使用got10k_model.pth和GOT10K的测试集进行测试时，在第176个数据时发生越界错误

运行log如下：
loading GOT10K: 100%|████████████████████████| 180/180 [00:03<00:00, 54.86it/s, GOT-10k_Test_000180]
(  1) Video: GOT-10k_Test_000001 Time:   7.0s Speed: 14.2fps
(  2) Video: GOT-10k_Test_000002 Time:   2.6s Speed: 30.7fps
(  3) Video: GOT-10k_Test_000003 Time:   1.9s Speed: 41.5fps
(  4) Video: GOT-10k_Test_000004 Time:   2.2s Speed: 31.7fps
(  5) Video: GOT-10k_Test_000005 Time:   2.4s Speed: 28.3fps
(  6) Video: GOT-10k_Test_000006 Time:   3.8s Speed: 25.8fps
(  7) Video: GOT-10k_Test_000007 Time:   3.1s Speed: 32.2fps
(  8) Video: GOT-10k_Test_000008 Time:   3.5s Speed: 28.1fps
......
(175) Video: GOT-10k_Test_000175 Time:   1.6s Speed: 56.3fps
Traceback (most recent call last):
  File "test.py", line 157, in <module>
    main()
  File "test.py", line 114, in main
    outputs = tracker.track(img, hp)
  File "../pysot/tracker/siamcar_tracker.py", line 165, in track
    max_r_up, max_c_up, new_cx, new_cy = self.getCenter(hp_score_up, p_score_up, scale_score, lrtbs)
  File "../pysot/tracker/siamcar_tracker.py", line 100, in getCenter
    score_up = self.coarse_location(hp_score_up, p_score_up, scale_score, lrtbs)
  File "../pysot/tracker/siamcar_tracker.py", line 85, in coarse_location
    bbox_region = lrtbs[max_r, max_c, :]
IndexError: index 25 is out of bounds for axis 0 with size 25

**Comment by huchenjie339** [comment]
解决了吗？我最近也遇到了这个问题。

**Comment by huchenjie339** [comment]
@Mionger 解决了吗？我最近也遇到了这个问题。

**Comment by hds-xb** [comment]
@huchenjie339 你好，请问你解决了吗，我也遇到这个问题了

**Comment by huchenjie339** [comment]
不好意思奥，我也没有解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ohhhyeahhh/SiamCAR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 上午10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ohhhyeahhh/SiamCAR] 测试时目标位置偏移相关的数组越界错误 (#57)





 
@huchenjie339 你好，请问你解决了吗，我也遇到这个问题了
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
