### ISSUE TITLE
测试过程UAV123更换其他数据集，出错

### ISSUE THREAD

**Issue by FMZCY** [ohhhyeahhh/SiamCAR#71]
将test.py中的数据集UAV123名字进行更换，出现：
Traceback (most recent call last):
  File "/home/fmz/SiamCAR-master/test.py", line 126, in <module>
    main()
  File "/home/fmz/SiamCAR-master/test.py", line 51, in main
    params = getattr(cfg.HP_SEARCH,args.dataset)
  File "/home/fmz/anaconda3/envs/SiamCAR/lib/python3.6/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: OTB50
希望能够解答，非常非常感谢！

**Comment by Capricorn231** [comment]
因为在我们test的配置文件中并没有给出OTB_50的超参设置，其中只有OTB100，GOT10k，Lasot和UAV123的超参。您可以试着在配置文件中增加OTB50的超参或者使用其他数据集。
