### ISSUE TITLE
eval问题

### ISSUE THREAD

**Issue by mezhia** [ohhhyeahhh/SiamCAR#76]
您好，请问我在运行eval文件时loading UAV123: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00, 62.44it/s, bike1]
eval success:   0%|                                                           | 0/1 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 

Traceback (most recent call last):
  File "F:\paper\SiamCAR-master(3)\SiamCAR-master3\toolkit\evaluation\ope_benchmark.py", line 50, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "F:\paper\SiamCAR-master(3)\SiamCAR-master3\toolkit\utils\statistics.py", line 34, in success_overlap
    iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed报错，请问是什么原因呢？

**Comment by job333** [comment]
> 
你好，这个问题解决了吗

**Comment by Lxzzzzzzzzzzz** [comment]
请问你们解决了吗，碰到了一样的问题@job333@mezhia

**Comment by 102447** [comment]
同问，有解决的嘛
