### ISSUE TITLE
测试过程中的问题

### ISSUE THREAD

**Issue by xyl-507** [ohhhyeahhh/SiamCAR#77]
作者您好：
感谢你们的杰出贡献。最近在复现你们的代码过程中出现一个问题。我用pysot的环境（torch==0.4）来跑您们的代码，训练完成之后，只有19个checkpoint，并且在**resume**和**test**的过程中，在**加载模型**时都出现了**assertion error**。
请问一下：是不是因为代码环境不一样？可是我看你们的介绍说在0torch==.4的环境中也实现了。

**Comment by xyl-507** [comment]
把torch换成1.2版本的确实可以测试了，成功运行。但现在一个问题就是，将backbone换成pysot中的mobilenetv2，训练过程没有出现问题，测试过程仍然报错：
assert key in deserialized_objects 
AssertionError
请问一下，是出了什么问题吗？

**Comment by job333** [comment]
> 
你好，可以交流一下吗，我把backbone换成alexnet，测试过程也报错了。qq1824553806
loading UAV123: 100%|██████████████████████████████████| 123/123 [00:10<00:00, 12.11it/s, person4_1]
Traceback (most recent call last):
  File "test.py", line 126, in <module>
    main()
  File "test.py", line 90, in main
    outputs = tracker.track(img, hp)
  File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\tracker\siamcar_tracker.py", line 123, in track
    outputs = self.model.track(x_crop)
  File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\models\model_builder.py", line 55, in track
    features = self.xcorr_depthwise(xf[0],self.zf[0])
  File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\utils\xcorr.py", line 44, in xcorr_depthwise
    x = x.view(1, batch*channel, x.size(2), x.size(3))
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

**Comment by xyl-507** [comment]
@job333 咱们的问题害不一样，你的模型已经加载成功了，我的在加载阶段就出错了。

**Comment by job333** [comment]
加下qq,我上面发了，再探讨一下这个问题

**Comment by job333** [comment]
@xyl-507

**Comment by WangJun-ZJUT** [comment]
> > 
> 
> 你好，可以交流一下吗，我把backbone换成alexnet，测试过程也报错了。qq1824553806 loading UAV123: 100%|██████████████████████████████████| 123/123 [00:10<00:00, 12.11it/s, person4_1] Traceback (most recent call last): File "test.py", line 126, in main() File "test.py", line 90, in main outputs = tracker.track(img, hp) File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\tracker\siamcar_tracker.py", line 123, in track outputs = self.model.track(x_crop) File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\models\model_builder.py", line 55, in track features = self.xcorr_depthwise(xf[0],self.zf[0]) File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\utils\xcorr.py", line 44, in xcorr_depthwise x = x.view(1, batch*channel, x.size(2), x.size(3)) IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

您好！关于这个问题是因为在resnet中融合了多层特征，backbone返回的是多层特征的列表，更换成alexnet后返回的是tensor，所以索引上会差一个维度。

**Comment by job333** [comment]
@WangJun-ZJUT 请教您这具体该怎么改，代码能力实在是差一些，感谢

**Comment by job333** [comment]
@WangJun-ZJUT 请教您这具体该怎么改，代码能力实在是差一些，感谢

**Comment by WangJun-ZJUT** [comment]
> @WangJun-ZJUT 请教您这具体该怎么改，代码能力实在是差一些，感谢

您好，在alexnet的输出套一层list就可以了

**Comment by xyl-507** [comment]
@WangJun-ZJUT 作者您好，请问一下换了mobilenetv2，训练可以，为什么测试会报错：
(pysot) xyl@xyl-System-Product-Name:~/SiamCAR-master/experiments/siamcar_mobilenetv2$ python -u ../../tools/test.py --snapshot snapshot/checkpoint_e8.pth --config config.yaml --dataset UAV123
Traceback (most recent call last):
File "../../tools/test.py", line 127, in 
main()
File "../../tools/test.py", line 61, in main
model = load_pretrain(model, args.snapshot).cuda().eval()
File "/home/xyl/SiamCAR-master/pysot/utils/model_load.py", line 51, in load_pretrain
map_location=lambda storage, loc: storage.cuda(device))
File "/home/xyl/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/serialization.py", line 358, in load
return _load(f, map_location, pickle_module)
File "/home/xyl/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/serialization.py", line 548, in _load
assert key in deserialized_objects
AssertionError

**Comment by xyl-507** [comment]
@WangJun-ZJUT 作者您好，我用resnet50为主干网络训练的siamcar在测试阶段只有checkpoint_e10,e15,e16，可以成功测试。其它的权重就会报错：
`RuntimeError: storage has wrong size: expected 5754537876681439371 got 16384`
or
`ValueError: unsupported pickle protocol: 128`
请问一下：这种是什么原因导致的？
十分感谢！！

**Comment by WangJun-ZJUT** [comment]
抱歉，我们没有遇见过这种情况，考虑是由于硬件问题引起的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月2日(周六) 晚上10:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ohhhyeahhh/SiamCAR] 测试过程中的问题 (Issue #77)




 
@WangJun-ZJUT 作者您好，我用resnet50为主干网络训练的siamcar在测试阶段只有checkpoint_e10,e15,e16，可以成功测试。其它的权重就会报错：
 RuntimeError: storage has wrong size: expected 5754537876681439371 got 16384
 or
 ValueError: unsupported pickle protocol: 128
 请问一下：这种是什么原因导致的？
 十分感谢！！

**Comment by xyl-507** [comment]
好的，十分感谢作者，确实是你们贡献很好，忍不住想试试，无奈呀，这么晚打扰你，抱歉了！哈哈哈。



| |
xueliangdongdong
|
|
***@***.***
前途很远很暗，不要怕，不怕的人前面才有路。
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月02日 23:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ohhhyeahhh/SiamCAR] 测试过程中的问题 (Issue #77) |

抱歉，我们没有遇见过这种情况，考虑是由于硬件问题引起的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月2日(周六) 晚上10:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ohhhyeahhh/SiamCAR] 测试过程中的问题 (Issue #77)





@WangJun-ZJUT 作者您好，我用resnet50为主干网络训练的siamcar在测试阶段只有checkpoint_e10,e15,e16，可以成功测试。其它的权重就会报错：
RuntimeError: storage has wrong size: expected 5754537876681439371 got 16384
or
ValueError: unsupported pickle protocol: 128
请问一下：这种是什么原因导致的？
十分感谢！！

**Comment by iYbei** [comment]
你好，我想问一下我在评估OTB100数据集上跑出来的结果出现了以下错误，是因为什么呢？跑出来的结果是100个txt文件
(base) at@at-RESCUER-R720-15IKBN:~/SiamCAR-master/tools$ python eval.py --tracker_path ./results --dataset UAV123 --tracker_prefix 'general_model'
Traceback (most recent call last):
  File "eval.py", line 104, in <module>
    main()
  File "eval.py", line 37, in main
    assert len(trackers) > 0
AssertionError

**Comment by iYbei** [comment]
你好，我想问一下我在评估OTB100数据集上跑出来的结果出现了以下错误，是因为什么呢？跑出来的结果是100个txt文件
(base) at@at-RESCUER-R720-15IKBN:~/SiamCAR-master/tools$ python eval.py --tracker_path ./results --dataset OTB100 --tracker_prefix 'general_model'
Traceback (most recent call last):
  File "eval.py", line 104, in <module>
    main()
  File "eval.py", line 37, in main
    assert len(trackers) > 0
AssertionError
