### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by job333** [ohhhyeahhh/SiamCAR#78]
在测试UAV123的时候，通过可视化发现，测试的速度特别满，这是正常的吗？希望得到您的回复十分感谢！

**Comment by WangJun-ZJUT** [comment]
您好！这是由于UAV的图像分辨率较大导致的，将可视化功能关闭就可以了。

**Comment by job333** [comment]
> 
感谢您的回复，关闭了可视化还是不行，我想把骨干网换成alexnet,修改了config.yaml和config.py中的骨干网名字为alexnet，报错Traceback (most recent call last):
  File "test.py", line 126, in <module>
    main()
  File "test.py", line 57, in main
    model = ModelBuilder()
  File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\models\model_builder.py", line 26, in __init__
    **cfg.BACKBONE.KWARGS)
  File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\models\backbone\__init__.py", line 23, in get_backbone
    return BACKBONES[name](**kwargs)
  File "E:\siamese-rpn-pytorch\za\SiamCAR-master\pysot\models\backbone\alexnet.py", line 91, in alexnet
    return AlexNet(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'used_layers'您再给看看怎么解决，谢谢！

**Comment by Capricorn231** [comment]
您好，这是因为alexnet与resnet中结构不同导致的配置文件输入有所不同，您可以参考[pysot](https://github.com/STVIR/pysot)中对应alexnet的配置文件对SiamCAR中的配置文件进行修改。
