### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by jing941** [ohhhyeahhh/SiamCAR#85]
你好，我单独使用coco数据集进行训练，出现如下错误是什么原因
      Traceback (most recent call last):
  File "/home/s/ymt/Siam-car/yuanCAR/SiamCAR-master/tools/train.py", line 315, in <module>
    main()
  File "/home/s/ymt/Siam-car/yuanCAR/SiamCAR-master/tools/train.py", line 288, in main
    train_loader = build_data_loader()
  File "/home/s/ymt/Siam-car/yuanCAR/SiamCAR-master/tools/train.py", line 61, in build_data_loader
    train_dataset = TrkDataset()
  File "/home/s/ymt/Siam-car/yuanCAR/SiamCAR-master/pysot/datasets/dataset.py", line 159, in __init__
    start
  File "/home/s/ymt/Siam-car/yuanCAR/SiamCAR-master/pysot/datasets/dataset.py", line 44, in __init__
    meta_data = self._filter_zero(meta_data)
  File "/home/s/ymt/Siam-car/yuanCAR/SiamCAR-master/pysot/datasets/dataset.py", line 76, in _filter_zero
    for frm, bbox in frames.items():
AttributeError: 'str' object has no attribute 'items'
期待您的回信，谢谢！

**Comment by sai-fu** [comment]
should convert data type

**Comment by sai-fu** [comment]
hello ,I use the got10k dataset to train alone, and the following error occurs
  File "D:\parcharm_pro\SiamCAR-master\pysot\utils\model_load.py", line 59, in load_pretrain
    check_keys(model, pretrained_dict)
  File "D:\parcharm_pro\SiamCAR-master\pysot\utils\model_load.py", line 35, in check_keys
    'load NONE from pretrained checkpoint'
AssertionError: load NONE from pretrained checkpoint

**Comment by jing941** [comment]
> Maybe the path to the pre-trained model could not be found

**Comment by chenxlin222** [comment]
您好，请问如果单独用got-10k数据集训练的话，__C.DATASET.GOT.NUM_USE (100000)， __C.DATASET.VIDEOS_PER_EPOCH (600000)，还有__C.TRAIN.EPOCH (20)，这些参数有改变吗？应该改成多少比较合适呢？
