### ISSUE TITLE
not able to test on UAV123 dataset

### ISSUE THREAD

**Issue by CassandraClare** [ohhhyeahhh/SiamCAR#93]
I am getting this error :

loading UAV123:   0%|                                             | 0/123 [00:00<?, ?it/s, group1_2][ WARN:0@4.830] global loadsave.cpp:244 findDecoder imread_('/content/SiamCAR/tools/../testing_dataset/UAV123/group1/001333.jpg'): can't open/read file: check file path/integrity

loading UAV123:   0%|                                             | 0/123 [00:00<?, ?it/s, group1_2]
Traceback (most recent call last):
  File "/content/SiamCAR/tools/test.py", line 126, in <module>
    main()
  File "/content/SiamCAR/tools/test.py", line 66, in main
    dataset = DatasetFactory.create_dataset(name=args.dataset,
  File "/content/SiamCAR/tools/../toolkit/datasets/__init__.py", line 25, in create_dataset
    dataset = UAVDataset(**kwargs)
  File "/content/SiamCAR/tools/../toolkit/datasets/uav.py", line 44, in __init__
    self.videos[video] = UAVVideo(video,
  File "/content/SiamCAR/tools/../toolkit/datasets/uav.py", line 23, in __init__
    super(UAVVideo, self).__init__(name, root, video_dir,
  File "/content/SiamCAR/tools/../toolkit/datasets/video.py", line 27, in __init__
    assert img is not None, self.img_names[0]
AssertionError: /content/SiamCAR/tools/../testing_dataset/UAV123/group1/001333.jpg

Please help.

**Comment by LLLLLLLloser** [comment]
> 我收到此错误：

同问怎么解决啊
